import type { FsHandle, RemoteContext } from '$lib/data/storage/storage-source-types';

import type { DBSchema } from 'idb';
import type { ReadingGoal } from '$lib/data/reading-goal';
import type { SyncEndpointType } from '$lib/data/storage/storage-types';

interface BooksDbV7BookData {
  id: number;
  title: string;
  language?: string;
  styleSheet: string;
  elementHtml: string;
  blobs: Record<string, Blob>;
  coverImage?: string | Blob;
  hasThumb: boolean;
  characters: number;
  sections?: Section[];
  lastBookModified: number;
  lastBookOpen: number;
  htmlBackup?: string;
  /**
   * The `sourceInstanceId` of the connected source under which we
   * last confirmed this book exists — set when a remote listing
   * returned its title, or when a push of its bookdata succeeded.
   * Compared against the active source's `sourceInstanceId` to
   * distinguish:
   *   - "deleted on another synced device" (id matches active source,
   *     title missing from listing) → prune.
   *   - "imported locally, not yet pushed" (no id) → keep; boot push
   *     mirrors it up.
   *   - "belongs to a different source instance" (id mismatch) →
   *     keep; the row is invariant to the prior source's deletions.
   * On boot push success / reconcile against current source, gets
   * (re)stamped with the active id.
   */
  lastSeenSourceInstanceId?: string;
}

interface BooksDbV7BookmarkData {
  dataId: number;
  scrollX?: number;
  scrollY?: number;
  exploredCharCount?: number;
  progress: number | string | undefined;
  completed?: boolean;
  lastBookmarkModified: number;
  /**
   * Set when the row was seeded by ensurePlaceholders from a sync
   * source's progress_* filename. The reading position is unknown
   * (no scrollY / exploredCharCount), so LocalReplicationEndpoint's
   * up-to-date check treats it as missing and the open-flow pulls
   * the real bookmark. Cleared on first overwrite by replicator →
   * saveProgress.
   */
  placeholder?: boolean;
}

interface BooksDbV7StorageSource {
  name: string;
  type: SyncEndpointType;
  data: FsHandle | RemoteContext;
  lastSourceModified: number;
  /**
   * UUID generated by source-manager every time a successful connect
   * commits this record. Each fresh connect rotates it (the picker
   * may have returned a different folder; an OAuth flow may have
   * returned a different account), so previously-mirrored book rows
   * whose `lastSeenSourceInstanceId` matches THIS id are still
   * eligible for cross-device deletion pruning, while rows tied to
   * an earlier id are inert. Old IDB records may lack this field —
   * `loadConnectionsFromDb` backfills with a fresh UUID on first
   * boot.
   */
  sourceInstanceId?: string;
}

interface BooksDbV7Statistic {
  title: string;
  dateKey: string;
  charactersRead: number;
  readingTime: number;
  minReadingSpeed: number;
  altMinReadingSpeed: number;
  lastReadingSpeed: number;
  maxReadingSpeed: number;
  lastStatisticModified: number;
  completedBook?: number;
  completedData?: Omit<BooksDbV7Statistic, 'title' | 'lastStatisticModified'>;
}

interface BooksDbV7ReadingGoal extends ReadingGoal {
  goalEndDate: string;
  goalOriginalEndDate: string;
}

interface BooksDbV7LastModified {
  title: string;
  dataType: string;
  lastModifiedValue: number;
}

export interface Section {
  reference: string;
  charactersWeight: number;
  label?: string;
  startCharacter?: number;
  characters?: number;
  parentChapter?: string;
}

export default interface BooksDbV7 extends DBSchema {
  data: {
    key: number;
    value: BooksDbV7BookData;
    indexes: {
      title: string;
    };
  };
  bookmark: {
    key: number;
    value: BooksDbV7BookmarkData;
    indexes: {
      dataId: number;
    };
  };
  lastItem: {
    key: number;
    value: {
      dataId: number;
    };
  };
  storageSource: {
    key: string;
    value: BooksDbV7StorageSource;
  };
  statistic: {
    key: string[];
    value: BooksDbV7Statistic;
    indexes: {
      dateKey: string;
      completedBook: (string | number | [])[];
    };
  };
  readingGoal: {
    key: string;
    value: BooksDbV7ReadingGoal;
    indexes: {
      goalEndDate: string;
    };
  };
  lastModified: {
    key: string[];
    value: BooksDbV7LastModified;
  };
}
