import type { FsHandle, RemoteContext } from '$lib/data/storage/storage-source-types';

import type { DBSchema } from 'idb';
import type { ReadingGoal } from '$lib/data/reading-goal';
import type { SyncEndpointType } from '$lib/data/storage/storage-types';

interface BooksDbV8BookData {
  id: number;
  title: string;
  author?: string;
  language?: string;
  styleSheet: string;
  elementHtml: string;
  blobs: Record<string, Blob>;
  coverImage?: string | Blob;
  hasThumb: boolean;
  characters: number;
  sections?: Section[];
  lastBookModified: number;
  lastBookOpen: number;
  htmlBackup?: string;
  /**
   * The `sourceInstanceId` of the connected source under which we
   * last confirmed this book exists — set when a remote listing
   * returned its title, or when a push of its bookdata succeeded.
   * Compared against the active source's `sourceInstanceId` to
   * distinguish:
   *   - "deleted on another synced device" (id matches active source,
   *     title missing from listing) → prune.
   *   - "imported locally, not yet pushed" (no id) → keep; boot push
   *     mirrors it up.
   *   - "belongs to a different source instance" (id mismatch) →
   *     keep; the row is invariant to the prior source's deletions.
   * On boot push success / reconcile against current source, gets
   * (re)stamped with the active id.
   */
  lastSeenSourceInstanceId?: string;
}

interface BooksDbV8BookmarkData {
  /**
   * Canonical book title — the app-wide book identity (also the sync
   * folder name and the `statistic` / `lastModified` key). Replaced
   * the v7 `dataId` foreign key to the `data` store's device-local
   * autoincrement id, so bookmarks survive delete + re-import and
   * serialize portably into remote `progress_*.json` files.
   */
  title: string;
  scrollX?: number;
  scrollY?: number;
  exploredCharCount?: number;
  progress: number | string | undefined;
  completed?: boolean;
  lastBookmarkModified: number;
  /**
   * Set when the row was seeded from a sync source's progress_*
   * filename. The reading position is unknown (no scrollY /
   * exploredCharCount), so LocalReplicationEndpoint's up-to-date
   * check treats it as missing and the open-flow pulls the real
   * bookmark. Cleared on first overwrite by replicator → saveProgress.
   */
  placeholder?: boolean;
}

interface BooksDbV8StorageSource {
  name: string;
  type: SyncEndpointType;
  data: FsHandle | RemoteContext;
  lastSourceModified: number;
  /**
   * UUID generated by source-manager every time a successful connect
   * commits this record. Each fresh connect rotates it (the picker
   * may have returned a different folder; an OAuth flow may have
   * returned a different account), so previously-mirrored book rows
   * whose `lastSeenSourceInstanceId` matches THIS id are still
   * eligible for cross-device deletion pruning, while rows tied to
   * an earlier id are inert. Old IDB records may lack this field —
   * `loadConnectionsFromDb` backfills with a fresh UUID on first
   * boot.
   */
  sourceInstanceId?: string;
}

interface BooksDbV8Statistic {
  title: string;
  dateKey: string;
  charactersRead: number;
  readingTime: number;
  minReadingSpeed: number;
  altMinReadingSpeed: number;
  lastReadingSpeed: number;
  maxReadingSpeed: number;
  lastStatisticModified: number;
  completedBook?: number;
  completedData?: Omit<BooksDbV8Statistic, 'title' | 'lastStatisticModified'>;
}

interface BooksDbV8ReadingGoal extends ReadingGoal {
  goalEndDate: string;
  goalOriginalEndDate: string;
}

interface BooksDbV8LastModified {
  title: string;
  dataType: string;
  lastModifiedValue: number;
}

interface BaseSection {
  reference: string;
  charactersWeight: number;
}

export interface ChapterSection extends BaseSection {
  label?: string;
  startCharacter: number;
  characters: number;
  parentChapter?: undefined;
}

export interface ChildSection extends BaseSection {
  parentChapter: string;
  label?: undefined;
  startCharacter?: undefined;
  characters?: undefined;
}

export type Section = ChapterSection | ChildSection;

export default interface BooksDbV8 extends DBSchema {
  data: {
    key: number;
    value: BooksDbV8BookData;
    indexes: {
      // Unique from v8 onward (`DBSchema` cannot express uniqueness);
      // the v8 upgrade dedupes same-title rows before recreating it.
      title: string;
    };
  };
  bookmark: {
    // Keyed by canonical title from v8 on. The v7 schema also declared a
    // `dataId` index here, but no `createIndex` call ever created it.
    key: string;
    value: BooksDbV8BookmarkData;
  };
  lastItem: {
    key: number;
    value: {
      title: string;
    };
  };
  storageSource: {
    key: string;
    value: BooksDbV8StorageSource;
  };
  statistic: {
    key: string[];
    value: BooksDbV8Statistic;
    indexes: {
      dateKey: string;
      completedBook: (string | number | [])[];
    };
  };
  readingGoal: {
    key: string;
    value: BooksDbV8ReadingGoal;
    indexes: {
      goalEndDate: string;
    };
  };
  lastModified: {
    key: string[];
    value: BooksDbV8LastModified;
  };
}
